Extract wmain() to new source file main.cpp
See merge request Linaro/WindowsPerf/windowsperf!198

=== ChangeLog ===

* wperf: fix error C3861: 'malloc': identifier not found

* wperf: remove unused headers from wperf.cpp

* wperf: move wmain() to a separate source file